name: PCCGM
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - joblib
  - tqdm
  - torch
  - torchvision
  - pytorch-lightning
  - Pillow
  - omegaconf
  - einops
  - typing-extensions
