name: PCCGM2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - fenics
  - matplotlib
  - joblib
  - tqdm
  - pytorch-lightning
  - Pillow
  - omegaconf
  - einops
  - typing-extensions
