model:
  target: models.cnn.CNNRegressor
  params:
    lr: 1e-3
    optimizer_type: "adam"  # ["adam", "adamw"]
    scheduler_type: "cos-warm"  # ["cos", "cos-warm", "mstep", "exp", "none"]
    milestones: [30, 80]  # only for mstep
    gamma: 0.5  # decay factor for mstep and exp
    in_channels: 1
    input_size: [64, 64]
    out_dim: 9
    n_feat: 64
    dropout: 0.
    grad: [False, False]  # [train, val & test]
    padding_mode: "circular"
    activation: "gelu"  # ["relu", "gelu", "tanh", "leakyrelu", "sigmoid"]
    share_weights: False

data:
  target: dataloaders.loaders.RVELoader
  params:
    data_dir: ../data/rve/domain_1.00x1.00_res_64x64_r_0.090-0.160_frac_0.05-0.80_keep_last_True_Em_71.00_nu_m_0.33_Ei_400.00_nu_i_0.25_seed_0
    batch_size: 32
    num_workers: 8
    total_samples: 100
    train_samples: 80
    val_samples: 10
    test_samples: 10
    grad: True

lightning:
  lock_base: False
  test: True
  trainer:
    accelerator: gpu
    strategy: ddp
    devices: 0,1
    precision: 16-mixed
    gradient_clip_val: 1.
    val_check_interval: 1.
    inference_mode: False  # set to False to enable gradient calculation during validation and testing
  epochs: 2000
  save_every_n_epochs: 5
  sample_every_n_steps: 20
