model:
  target: models.score_matching.DiffusionSDERVE
  params:
    lr: 1e-4
    optimizer_type: "adam"  # ["adam", "adamw"]
    scheduler_type: "none"  # ["cos", "cos-warm", "mstep", "exp", "none"]
    milestones: [30, 80]  # only for mstep
    gamma: 0.5  # decay factor for mstep and exp
    residual_enable: True
    residual_weight: 0.1
    unet_config:
      target: models.unets.UNET1
      params:
        in_channels: 1
        n_feat: 256
        pool_size: 4
        data_size: 64
        cond_size: 9
        controlnet:
          use: True
          condition_encoder:
            target: models.unets.CondVec2Img
            params:
              cond_size: 9
              data_size: 64
              channels: 2
    sde_config:
      target: sdes.forward.VP
      params:
        beta_min: 1e-4
        beta_max: 10
    sampler_config:
      target: sdes.backward.ProbabilityFlowODE
      params:
        num_time_steps: 2000
        eps: 1e-5
    residual_config:
      target: physics.operators.RVE
      params:
        properties: [71, 0.33, 400, 0.25]
        corner: [1.0, 1.0]
        n_cells: [64, 64]

data:
  target: dataloaders.loaders.RVELoader
  params:
    data_dir: ../data/rve/domain_1.00x1.00_res_64x64_r_0.090-0.160_frac_0.05-0.80_keep_last_True_Em_71.00_nu_m_0.33_Ei_400.00_nu_i_0.25_seed_0
    batch_size: 32
    num_workers: 8
    total_samples: 10000
    train_samples: 100
    val_samples: 10
    test_samples: 2

lightning:
  lock_base: True
  trainer:
    accelerator: gpu
    strategy: ddp
    devices: 0,1
    precision: 16-mixed
  epochs: 10
  save_every_n_epochs: 5
  sample_every_n_steps: 20
